# Generated by Django 5.1.6 on 2025-02-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackerModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "locations",
                    models.CharField(
                        help_text="Введите где хотите выполнять действие", max_length=255, verbose_name="Место"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Введите во сколько хотите выполнять действие", verbose_name="Время выполнения"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Введите действие из котрого хотите сформировать привычку",
                        max_length=255,
                        verbose_name="Действие/привычка",
                    ),
                ),
                (
                    "is_nice",
                    models.BooleanField(
                        help_text="Отметьте, если привычка приятная", verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        help_text="Периодичность выполнения действия", verbose_name="Периодичность"
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Вознаграждение за выполнение действия",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        help_text="Максимальное время на выполнение 120 секунд", verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        help_text="Отметка, для общего пользования", verbose_name="Признак публичности"
                    ),
                ),
                (
                    "associated_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберете привычку из приятных",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit",
                        to="tracker.trackermodel",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трекер привычек",
                "verbose_name_plural": "Трекер привычек",
            },
        ),
    ]
