# Generated by Django 5.1.6 on 2025-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackermodel",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Вознаграждение за выполнение действия",
                max_length=255,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
